name: Lint

env:
  SETUP_GO_VERSION: '^1.18'

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.46
          args: --timeout=10m --config=.golangci.json
